//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameruImagesUploader.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameruImagesUploader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additionally.
        /// </summary>
        public static string Additionally {
            get {
                return ResourceManager.GetString("Additionally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All rights reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All types.
        /// </summary>
        public static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoRun.
        /// </summary>
        public static string AutoRun {
            get {
                return ResourceManager.GetString("AutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bitcoin.
        /// </summary>
        public static string Bitcoin {
            get {
                return ResourceManager.GetString("Bitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom narrow row.
        /// </summary>
        public static string ColorBottomNarrowRow {
            get {
                return ResourceManager.GetString("ColorBottomNarrowRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buttons background.
        /// </summary>
        public static string ColorButtonBackground {
            get {
                return ResourceManager.GetString("ColorButtonBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buttons highlighted.
        /// </summary>
        public static string ColorButtonBackgroundHighlighted {
            get {
                return ResourceManager.GetString("ColorButtonBackgroundHighlighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combobox background.
        /// </summary>
        public static string ColorComboBoxBackground {
            get {
                return ResourceManager.GetString("ColorComboBoxBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combobox highlighted.
        /// </summary>
        public static string ColorComboBoxBackgroundHighlighted {
            get {
                return ResourceManager.GetString("ColorComboBoxBackgroundHighlighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combobox foreground.
        /// </summary>
        public static string ColorComboBoxForeground {
            get {
                return ResourceManager.GetString("ColorComboBoxForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combobox item background.
        /// </summary>
        public static string ColorComboBoxItemBackground {
            get {
                return ResourceManager.GetString("ColorComboBoxItemBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combobox Item highlighted.
        /// </summary>
        public static string ColorComboBoxItemBackgroundHighlighted {
            get {
                return ResourceManager.GetString("ColorComboBoxItemBackgroundHighlighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Labels foregroung.
        /// </summary>
        public static string ColorLabelForegroung {
            get {
                return ResourceManager.GetString("ColorLabelForegroung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status bar label.
        /// </summary>
        public static string ColorLabelStatusBar {
            get {
                return ResourceManager.GetString("ColorLabelStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Listbox background.
        /// </summary>
        public static string ColorListBoxBackground {
            get {
                return ResourceManager.GetString("ColorListBoxBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle row.
        /// </summary>
        public static string ColorMiddleRow {
            get {
                return ResourceManager.GetString("ColorMiddleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Picker.
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Progress bar background.
        /// </summary>
        public static string ColorProgressBarBackground {
            get {
                return ResourceManager.GetString("ColorProgressBarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Progress bar foreground.
        /// </summary>
        public static string ColorProgressBarForeground {
            get {
                return ResourceManager.GetString("ColorProgressBarForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color scheme.
        /// </summary>
        public static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Textbox background.
        /// </summary>
        public static string ColorTextBoxBackground {
            get {
                return ResourceManager.GetString("ColorTextBoxBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Textbox foreground.
        /// </summary>
        public static string ColorTextBoxForeground {
            get {
                return ResourceManager.GetString("ColorTextBoxForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top narrow row.
        /// </summary>
        public static string ColorTopNarrowRow {
            get {
                return ResourceManager.GetString("ColorTopNarrowRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top wide row.
        /// </summary>
        public static string ColorTopWideRow {
            get {
                return ResourceManager.GetString("ColorTopWideRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context menu.
        /// </summary>
        public static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload to Images.Gameru.Net.
        /// </summary>
        public static string ContextMenuTitle {
            get {
                return ResourceManager.GetString("ContextMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gameru_pass_hash.
        /// </summary>
        public static string CookieNamePasswordHash {
            get {
                return ResourceManager.GetString("CookieNamePasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gameru_session_id.
        /// </summary>
        public static string CookieNameSessionId {
            get {
                return ResourceManager.GetString("CookieNameSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gameru_member_id.
        /// </summary>
        public static string CookieNameUserId {
            get {
                return ResourceManager.GetString("CookieNameUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically copy links to clipboard.
        /// </summary>
        public static string CopyLinksAutomatically {
            get {
                return ResourceManager.GetString("CopyLinksAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copyright © 2014-2015 Mikhail Gribanov.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Direct link.
        /// </summary>
        public static string DirectLink {
            get {
                return ResourceManager.GetString("DirectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for using this free program! If you like it you can make a donation..
        /// </summary>
        public static string DonateDescription {
            get {
                return ResourceManager.GetString("DonateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Donate.
        /// </summary>
        public static string DonateTitle {
            get {
                return ResourceManager.GetString("DonateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For forums (BB-code).
        /// </summary>
        public static string ForForums {
            get {
                return ResourceManager.GetString("ForForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://www.gameru.net/.
        /// </summary>
        public static string GameruLink {
            get {
                return ResourceManager.GetString("GameruLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gameru.net.
        /// </summary>
        public static string GameruName {
            get {
                return ResourceManager.GetString("GameruName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GB.
        /// </summary>
        public static string Gigabyte {
            get {
                return ResourceManager.GetString("Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/gmikhail/GameruImagesUploader/.
        /// </summary>
        public static string GithubLink {
            get {
                return ResourceManager.GetString("GithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GitHub.
        /// </summary>
        public static string GithubName {
            get {
                return ResourceManager.GetString("GithubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HTML code.
        /// </summary>
        public static string HTMLCode {
            get {
                return ResourceManager.GetString("HTMLCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon IconDefaultAvatar {
            get {
                object obj = ResourceManager.GetObject("IconDefaultAvatar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon IconInfo {
            get {
                object obj = ResourceManager.GetObject("IconInfo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon IconLogo {
            get {
                object obj = ResourceManager.GetObject("IconLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon IconSettings {
            get {
                object obj = ResourceManager.GetObject("IconSettings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageAdd {
            get {
                object obj = ResourceManager.GetObject("ImageAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageAvatarBorder {
            get {
                object obj = ResourceManager.GetObject("ImageAvatarBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageAvatarOpacityMask {
            get {
                object obj = ResourceManager.GetObject("ImageAvatarOpacityMask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageColors {
            get {
                object obj = ResourceManager.GetObject("ImageColors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageCopyLink {
            get {
                object obj = ResourceManager.GetObject("ImageCopyLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageDefaultAvatar {
            get {
                object obj = ResourceManager.GetObject("ImageDefaultAvatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageDelete {
            get {
                object obj = ResourceManager.GetObject("ImageDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://images.gameru.net/profile.
        /// </summary>
        public static string ImageHostingLink {
            get {
                return ResourceManager.GetString("ImageHostingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile on image hosting.
        /// </summary>
        public static string ImageHostingName {
            get {
                return ResourceManager.GetString("ImageHostingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageInfo {
            get {
                object obj = ResourceManager.GetObject("ImageInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageLogo {
            get {
                object obj = ResourceManager.GetObject("ImageLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageSettings {
            get {
                object obj = ResourceManager.GetObject("ImageSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images per line.
        /// </summary>
        public static string ImagesPerLine {
            get {
                return ResourceManager.GetString("ImagesPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageUpload {
            get {
                object obj = ResourceManager.GetObject("ImageUpload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integration.
        /// </summary>
        public static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interface.
        /// </summary>
        public static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KB.
        /// </summary>
        public static string Kilobyte {
            get {
                return ResourceManager.GetString("Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files.
        /// </summary>
        public static string LabelStatusBarFiles {
            get {
                return ResourceManager.GetString("LabelStatusBarFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        public static string LabelStatusBarReady {
            get {
                return ResourceManager.GetString("LabelStatusBarReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string LabelStatusBarSize {
            get {
                return ResourceManager.GetString("LabelStatusBarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading.
        /// </summary>
        public static string LabelStatusBarUploading {
            get {
                return ResourceManager.GetString("LabelStatusBarUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic detection.
        /// </summary>
        public static string LanguageDefault {
            get {
                return ResourceManager.GetString("LanguageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes will take effect after application restart. Restart now?.
        /// </summary>
        public static string LanguageInformation {
            get {
                return ResourceManager.GetString("LanguageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -hide.
        /// </summary>
        public static string LaunchKeyHide {
            get {
                return ResourceManager.GetString("LaunchKeyHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -upload.
        /// </summary>
        public static string LaunchKeyUpload {
            get {
                return ResourceManager.GetString("LaunchKeyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://opensource.org/licenses/mit-license.php.
        /// </summary>
        public static string LicenseLink {
            get {
                return ResourceManager.GetString("LicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License.
        /// </summary>
        public static string LicenseName {
            get {
                return ResourceManager.GetString("LicenseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Links type.
        /// </summary>
        public static string LinksType {
            get {
                return ResourceManager.GetString("LinksType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check entered data and try again.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://www.gameru.net/forum/index.php?act=Login&amp;CODE=01.
        /// </summary>
        public static string LoginUrl {
            get {
                return ResourceManager.GetString("LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show logo.
        /// </summary>
        public static string LogoVisibility {
            get {
                return ResourceManager.GetString("LogoVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make screenshots.
        /// </summary>
        public static string MakeScreenshots {
            get {
                return ResourceManager.GetString("MakeScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MB.
        /// </summary>
        public static string Megabyte {
            get {
                return ResourceManager.GetString("Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This service is limited to 3 megabytes to unauthorized users. Login?.
        /// </summary>
        public static string MessageImageSizeLimit {
            get {
                return ResourceManager.GetString("MessageImageSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All settings will be reset. Are you sure?.
        /// </summary>
        public static string MessageResetSettings {
            get {
                return ResourceManager.GetString("MessageResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The server returned an error. Maybe image is too large or the type is not recognized.
        /// </summary>
        public static string MessageServerError {
            get {
                return ResourceManager.GetString("MessageServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No resize.
        /// </summary>
        public static string NoResize {
            get {
                return ResourceManager.GetString("NoResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No rotate.
        /// </summary>
        public static string NoRotate {
            get {
                return ResourceManager.GetString("NoRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification area.
        /// </summary>
        public static string NotificationArea {
            get {
                return ResourceManager.GetString("NotificationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images uploaded.
        /// </summary>
        public static string NotifyImagesUploaded {
            get {
                return ResourceManager.GetString("NotifyImagesUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Links copy to clipboard.
        /// </summary>
        public static string NotifyLinksCopy {
            get {
                return ResourceManager.GetString("NotifyLinksCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options uploading image.
        /// </summary>
        public static string OptionsUploadingImage {
            get {
                return ResourceManager.GetString("OptionsUploadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images uploader for Gameru.net.
        /// </summary>
        public static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gameru Images Uploader.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://www.gameru.net/forum/index.php?act=Reg.
        /// </summary>
        public static string RegistrationLink {
            get {
                return ResourceManager.GetString("RegistrationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Will restore the original program settings.
        /// </summary>
        public static string ResetSettingsDescription {
            get {
                return ResourceManager.GetString("ResetSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore password.
        /// </summary>
        public static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://www.gameru.net/forum/index.php?act=Reg&amp;CODE=10.
        /// </summary>
        public static string RestorePasswordLink {
            get {
                return ResourceManager.GetString("RestorePasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 180°.
        /// </summary>
        public static string Rotate180 {
            get {
                return ResourceManager.GetString("Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 270°.
        /// </summary>
        public static string Rotate270 {
            get {
                return ResourceManager.GetString("Rotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 90°.
        /// </summary>
        public static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshot.
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshots.
        /// </summary>
        public static string Screenshots {
            get {
                return ResourceManager.GetString("Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When closing minimize to the notification area.
        /// </summary>
        public static string SettingsClose {
            get {
                return ResourceManager.GetString("SettingsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When minimized minimize to the notification area.
        /// </summary>
        public static string SettingsMinimize {
            get {
                return ResourceManager.GetString("SettingsMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show a friends.
        /// </summary>
        public static string ShowAFriends {
            get {
                return ResourceManager.GetString("ShowAFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1024x768.
        /// </summary>
        public static string Size1024 {
            get {
                return ResourceManager.GetString("Size1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1920x1080.
        /// </summary>
        public static string Size1080 {
            get {
                return ResourceManager.GetString("Size1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1280x720.
        /// </summary>
        public static string Size1280 {
            get {
                return ResourceManager.GetString("Size1280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 150x112.
        /// </summary>
        public static string Size150 {
            get {
                return ResourceManager.GetString("Size150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1600x1200.
        /// </summary>
        public static string Size1600 {
            get {
                return ResourceManager.GetString("Size1600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 320x240.
        /// </summary>
        public static string Size320 {
            get {
                return ResourceManager.GetString("Size320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 500x375.
        /// </summary>
        public static string Size500 {
            get {
                return ResourceManager.GetString("Size500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 64x64.
        /// </summary>
        public static string Size64 {
            get {
                return ResourceManager.GetString("Size64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 640x480.
        /// </summary>
        public static string Size640 {
            get {
                return ResourceManager.GetString("Size640", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 800x600.
        /// </summary>
        public static string Size800 {
            get {
                return ResourceManager.GetString("Size800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image thumbs size.
        /// </summary>
        public static string ThumbsSize {
            get {
                return ResourceManager.GetString("ThumbsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload images automatically.
        /// </summary>
        public static string UploadImagesAutomatically {
            get {
                return ResourceManager.GetString("UploadImagesAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://images.gameru.net/image/upload.
        /// </summary>
        public static string UploadUrl {
            get {
                return ResourceManager.GetString("UploadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WebMoney.
        /// </summary>
        public static string Webmoney {
            get {
                return ResourceManager.GetString("Webmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yandex.Money.
        /// </summary>
        public static string YandexMoney {
            get {
                return ResourceManager.GetString("YandexMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string СolorSchemeDark {
            get {
                return ResourceManager.GetString("СolorSchemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string СolorSchemeDefault {
            get {
                return ResourceManager.GetString("СolorSchemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string СolorSchemeLight {
            get {
                return ResourceManager.GetString("СolorSchemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modified.
        /// </summary>
        public static string СolorSchemeModified {
            get {
                return ResourceManager.GetString("СolorSchemeModified", resourceCulture);
            }
        }
    }
}
