//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameruImagesUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFB21301")]
        public global::System.Windows.Media.SolidColorBrush ColorTopWideRow {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorTopWideRow"]));
            }
            set {
                this["ColorTopWideRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF910F00")]
        public global::System.Windows.Media.SolidColorBrush ColorTopNarrowRow {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorTopNarrowRow"]));
            }
            set {
                this["ColorTopNarrowRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush ColorMiddleRow {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorMiddleRow"]));
            }
            set {
                this["ColorMiddleRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF910F00")]
        public global::System.Windows.Media.SolidColorBrush ColorBottomNarrowRow {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorBottomNarrowRow"]));
            }
            set {
                this["ColorBottomNarrowRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush ColorProgressBarBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorProgressBarBackground"]));
            }
            set {
                this["ColorProgressBarBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF06B025")]
        public global::System.Windows.Media.SolidColorBrush ColorProgressBarForeground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorProgressBarForeground"]));
            }
            set {
                this["ColorProgressBarForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush ColorListBoxBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorListBoxBackground"]));
            }
            set {
                this["ColorListBoxBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush ColorTextBoxBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorTextBoxBackground"]));
            }
            set {
                this["ColorTextBoxBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.SolidColorBrush ColorTextBoxForeground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorTextBoxForeground"]));
            }
            set {
                this["ColorTextBoxForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.SolidColorBrush ColorLabelForegroung {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorLabelForegroung"]));
            }
            set {
                this["ColorLabelForegroung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush ColorLabelStatusBar {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorLabelStatusBar"]));
            }
            set {
                this["ColorLabelStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFB21301")]
        public global::System.Windows.Media.SolidColorBrush ColorButtonBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorButtonBackground"]));
            }
            set {
                this["ColorButtonBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD01600")]
        public global::System.Windows.Media.SolidColorBrush ColorButtonBackgroundHighlighted {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorButtonBackgroundHighlighted"]));
            }
            set {
                this["ColorButtonBackgroundHighlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF910F00")]
        public global::System.Windows.Media.SolidColorBrush ColorComboBoxItemBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorComboBoxItemBackground"]));
            }
            set {
                this["ColorComboBoxItemBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD01600")]
        public global::System.Windows.Media.SolidColorBrush ColorComboBoxItemBackgroundHighlighted {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorComboBoxItemBackgroundHighlighted"]));
            }
            set {
                this["ColorComboBoxItemBackgroundHighlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush ColorComboBoxForeground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorComboBoxForeground"]));
            }
            set {
                this["ColorComboBoxForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFB21301")]
        public global::System.Windows.Media.SolidColorBrush ColorComboBoxBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorComboBoxBackground"]));
            }
            set {
                this["ColorComboBoxBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD01600")]
        public global::System.Windows.Media.SolidColorBrush ColorComboBoxBackgroundHighlighted {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColorComboBoxBackgroundHighlighted"]));
            }
            set {
                this["ColorComboBoxBackgroundHighlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources/ImageDefaultAvatar.png")]
        public string AvatarPath {
            get {
                return ((string)(this["AvatarPath"]));
            }
            set {
                this["AvatarPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordHash {
            get {
                return ((string)(this["PasswordHash"]));
            }
            set {
                this["PasswordHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserID {
            get {
                return ((string)(this["UserID"]));
            }
            set {
                this["UserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ImagesPerLine {
            get {
                return ((int)(this["ImagesPerLine"]));
            }
            set {
                this["ImagesPerLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotificationAreaMinimize {
            get {
                return ((bool)(this["NotificationAreaMinimize"]));
            }
            set {
                this["NotificationAreaMinimize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotificationAreaClose {
            get {
                return ((bool)(this["NotificationAreaClose"]));
            }
            set {
                this["NotificationAreaClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogoVisibility {
            get {
                return ((bool)(this["LogoVisibility"]));
            }
            set {
                this["LogoVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MakeScreenshots {
            get {
                return ((bool)(this["MakeScreenshots"]));
            }
            set {
                this["MakeScreenshots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyLinksAutomatically {
            get {
                return ((bool)(this["CopyLinksAutomatically"]));
            }
            set {
                this["CopyLinksAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UploadImagesAutomatically {
            get {
                return ((bool)(this["UploadImagesAutomatically"]));
            }
            set {
                this["UploadImagesAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRun {
            get {
                return ((bool)(this["AutoRun"]));
            }
            set {
                this["AutoRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContextMenu {
            get {
                return ((bool)(this["ContextMenu"]));
            }
            set {
                this["ContextMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ItemSize {
            get {
                return ((int)(this["ItemSize"]));
            }
            set {
                this["ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int СolorScheme {
            get {
                return ((int)(this["СolorScheme"]));
            }
            set {
                this["СolorScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
    }
}
